### ISSUE TITLE
How to install and use bunq tinker in laravel?

### ISSUE THREAD

**Issue by jimkaler** [bunq/tinker_php#17] opened 2018-04-07 06:44 UTC
Hey guys, i need to know how can we use bunq tinker in laravel project?

What I've done so far, Installed tinker in new directory because when I try to run "bash <(curl -s https://tinker.bunq.com/php/setup.sh)" command it was saying " _Please run the script from an empty directory_". 
And I've moved tinker folder in laravel vendor. But whenever i try to use BunqLib class in controller it giving me error "_Class 'bunq\tinker\BunqLib' not found_".
I have also tried with providers and alias in app.php but same error "_class not found_"
I'm stuck in bunq. I need help, Is anyone bunq expert here who can help me out?
Here the screenshot of error:
@OGKevin 
![screenshot from 2018-04-07 12-18-02](https://user-images.githubusercontent.com/36437555/38452245-cedb5222-3a5d-11e8-8b27-2cb143e97092.png)

**Comment by OGKevin** [comment] 2018-04-07 07:17
@jimkaler tinker is a command line tool and should not be used in a larval project unless your using it to execute command line commands like `tinker/user-overview`.

You should consider using [bunq/sdk_php] for this instead of tinker. You can then use [BunqLib.php](https://github.com/bunq/tinker_php/blob/26dd869e7991ec06906a7dcd69739919392a2cea/src/BunqLib.php) as example on how to use the [bunq/sdk_php].

Closing this issue as its not a bug. Feel free to continue commenting. 

[bunq/sdk_php]: http://www.github.com/bunq/sdk_php

**Closed as completed by OGKevin** 2018-04-07 07:17 UTC

**Comment by jimkaler** [comment] 2018-04-07 07:42
Thanks @OGKevin It was so complicated. Now I have found a way to implement it.
Thanks a lot.

**Comment by Shohan494** [comment] 2021-10-20 13:59
@jimkaler can you help me explaining the integration 😅
